#!/bin/bash
# Wrapper around the upstream giovtorres entrypoint for slurmd-gpu mode.
#
# Why this exists: the giovtorres image's Slurm 25.11 build is not linked
# against NVML, so slurmd's gres/gpu plugin cannot auto-enumerate CUDA
# devices on its own. Without /etc/slurm/gres.conf, slurmctld marks the
# node INVALID_REG with "gres/gpu count reported lower than configured
# (0 < N)" and every gpu submit is rejected with error 2072.
#
# The fix is to drop a gres.conf listing each /dev/nvidia[0-9] device
# the NVIDIA Container Runtime exposed to us. NodeName=g[1-64] covers
# every replica the upstream entrypoint can produce (it derives g${N}
# from the compose replica number).
set -e

if [ "$1" = "slurmd-gpu" ]; then
    gres_lines=""
    for dev in /dev/nvidia[0-9]; do
        [ -e "$dev" ] || continue
        gres_lines+="NodeName=g[1-64] Name=gpu Type=nvidia File=${dev}"$'\n'
    done

    if [ -n "${gres_lines}" ]; then
        {
            echo "# Auto-generated by entrypoint-gpu.sh at container start."
            echo "# Lists the NVIDIA device files the container saw at boot."
            printf '%s' "${gres_lines}"
        } > /etc/slurm/gres.conf
        chown slurm:slurm /etc/slurm/gres.conf 2>/dev/null || true
        chmod 0644 /etc/slurm/gres.conf
        echo "---> wrote /etc/slurm/gres.conf with $(echo "${gres_lines}" | wc -l) GPU entries"
    else
        echo "---> WARNING: no /dev/nvidia[0-9] devices visible; the NVIDIA Container Toolkit may not be configured. slurmd will register with Gres=gpu:nvidia:0 and slurmctld will mark the node INVALID_REG."
    fi
fi

exec /usr/local/bin/docker-entrypoint.sh "$@"
