#!/bin/bash
# Wrapper around the upstream giovtorres entrypoint for slurmd-gpu mode.
#
# Why this exists: the giovtorres image's Slurm 25.11 build is not linked
# against NVML, so slurmd's gres/gpu plugin cannot auto-enumerate CUDA
# devices on its own. Without /etc/slurm/gres.conf, slurmctld marks the
# node INVALID_REG with "gres/gpu count reported lower than configured
# (0 < N)" and every gpu submit is rejected with error 2072.
#
# The fix is to drop a gres.conf listing each /dev/nvidiaN device the
# NVIDIA Container Runtime exposed to us. NodeName=g[1-64] covers every
# replica the upstream entrypoint can produce (it derives g${N} from the
# compose replica number).
#
# For any command other than slurmd-gpu this script is a transparent
# pass-through, so the gpu image stays safe to reuse for other roles.
set -e

if [ "$1" = "slurmd-gpu" ]; then
    gres_lines=""
    # Match /dev/nvidia0, /dev/nvidia12, ... but NOT /dev/nvidiactl,
    # /dev/nvidia-uvm, /dev/nvidia-modeset. A bracket glob like
    # /dev/nvidia[0-9] would silently cap at 10 devices, so iterate the
    # wildcard and filter on a full-match regex instead.
    for dev in /dev/nvidia*; do
        [ -e "$dev" ] || continue
        [[ "$dev" =~ ^/dev/nvidia[0-9]+$ ]] || continue
        gres_lines+="NodeName=g[1-64] Name=gpu Type=nvidia File=${dev}"$'\n'
    done

    if [ -z "${gres_lines}" ]; then
        # Fail fast: the README's stated invariant is that this sample
        # only runs on a GPU host. Falling through here would let slurmd
        # register Gres=gpu:nvidia:0, the container would report healthy
        # (pidof slurmd succeeds), and the gpu partition would silently
        # never schedule. A hard exit surfaces the misconfiguration in
        # `docker compose ps` / deploy logs instead.
        echo "---> FATAL: slurmd-gpu requested but no /dev/nvidiaN devices are visible." >&2
        echo "            The NVIDIA Container Toolkit / driver is not set up on this host." >&2
        echo "            See the slurm-rest-api README 'Host prerequisites' section." >&2
        exit 1
    fi

    {
        echo "# Auto-generated by entrypoint-gpu.sh at container start."
        echo "# Lists the NVIDIA device files the container saw at boot."
        printf '%s' "${gres_lines}"
    } > /etc/slurm/gres.conf
    chown slurm:slurm /etc/slurm/gres.conf 2>/dev/null || true
    chmod 0644 /etc/slurm/gres.conf
    echo "---> wrote /etc/slurm/gres.conf with $(printf '%s' "${gres_lines}" | grep -c .) GPU entries"
fi

exec /usr/local/bin/docker-entrypoint.sh "$@"
