ClusterName=conoha
SlurmctldHost=slurm

AuthType=auth/munge
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/var/spool/slurm/jwt_hs256.key

CredType=cred/munge

SlurmUser=slurm
SlurmdUser=root

StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
SlurmctldPidFile=/var/spool/slurm/slurmctld.pid
SlurmdPidFile=/var/spool/slurm/slurmd.pid

SlurmctldPort=6817
SlurmdPort=6818

ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
ReturnToService=2

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
AccountingStoragePort=6819
AccountingStoreFlags=job_comment

JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

NodeName=slurm CPUs=2 RealMemory=1024 State=UNKNOWN
PartitionName=debug Nodes=slurm Default=YES MaxTime=INFINITE State=UP
