# Dex OIDC provider configuration.
# https://dexidp.io/docs/
# Placeholders (__VAR__) are replaced by sed in compose.yml entrypoint.

issuer: https://__DEX_ISSUER_HOST__/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: __OIDC_CLIENT_ID__
    redirectURIs:
      - "https://__OUTLINE_HOST__/auth/oidc.callback"
    name: Outline
    secret: __OIDC_CLIENT_SECRET__

enablePasswordDB: true

staticPasswords:
  - email: admin@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: admin
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
